apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: user
  namespace: siyu
spec:
  rules:
    - host: siyu.d.blueshark.com
      http:
        paths:
          - backend:
              serviceName: user
              servicePort: 8080
