apiVersion: v1
kind: ConfigMap
metadata:
  name: user-conf
  namespace: siyu
data:
  app.yml: |
    runmode: test # 运行模式 dev 开发环境 test 测试环境 debug debug环境 prod 正式环境
    logger:
      level: debug # default log level, used if hooks not specify a log level
      reportcaller: true # show reportcaller, will affect all hooks
      formatter: # default formatter, used if hooks not specify a formatter
        name: classic # default formatter name
        opts: # default formatter opts
          forcecolors: true
          truncateCallerPath: true
          callerPathStrip: true
      stdout:
        enabled: true
        level: debug
      udp:
        enabled: false
        level: debug
        service: logservice.siyu:8080
        formatter:
          name: classic
          opts: # default formatter opts
            truncateCallerPath: true
            callerPathStrip: true
      file:
        enabled: true
        name: user.log
        path: /app/log/user
        level: debug
        formatter:
          name: classic
          opts: # default formatter opts
            forcecolors: true
            truncateCallerPath: true
            callerPathStrip: true

    app:
      addr: ":8080"
    pg:
      user:
        url: "postgres://postgres:iLoveShark@master.postgresql/master?sslmode=disable&fallback_application_name=user"
        maxopen: 10
        maxidle: 5
    redis:
      sentinels:
        - redis-cluster-announce-0.redis-ha:26379
        - redis-cluster-announce-1.redis-ha:26379
        - redis-cluster-announce-2.redis-ha:26379
      addr: "redis.redis:6379"
    sms:
      addr: "http://sms.sg-base:8080/sms/send"
    voice:
      addr: "http://sms.sg-base:8080/voice/send"
    email:
      addr: "http://sms.sg-base:8080/email/send"
    fileupload:
      addr: "http://file.sg-base:8080/upload"
    filedownload:
      addr: "https://storageapi.oss-cn-zhangjiakou.aliyuncs.com"
    memberpoints:
      addr: "http://memberpoints:8080"
    channels:
      addr: "http://channels:8080"
    minapp:
      wx18cacb2235c01f99: 7b88ad6ee6b5f1d3a72ddaf359d7ea58 # 未知
      wxd7244a8a622667c4: 5d06ed3c520ee69b225a67928016c67b # 海洋个人测试用
      wxe73b9412731694b5: 98aaeaeaa45e20232a72bb9d254701a7 # 蓝鲨购车
      wx1b7f3eab81a75f67: f2c1e852efb5ea3a818d4b8806ea4964 #  简化版
      wxc8c06a041f93e997: 2b97ac29bf4e6135da59e9d566246100 # 所友俱乐部
    mq:
      kafka: kafka-headless.kafka:9092
    encrypt: false #敏感数据加密 GDPR 欧洲服务器数据加密
    state:
      0: Ok
      1: InvalidParameter
      2: Failed
      3: CrossDomainPrelight
      4: NoRecord
      5: Duplicate
      6: NotAuth