apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: siyu
spec:
  ports:
  - name: http-port
    port: 8080
    targetPort: 8080
  selector:
    app: user
  sessionAffinity: None
  type: ClusterIP
